/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.lista8.view;

import com.mycompany.lista8.model.Professor;
import com.mycompany.lista8.model.Titulacao;
import com.mycompany.lista8.model.Turma;
import com.mycompany.lista8.model.Turno;
import javax.swing.JOptionPane;

/**
 *
 * @author liandrar
 */
public class AppUi extends javax.swing.JFrame {

    Turma turma = new Turma();
    Professor professor = null;
    /**
     * Creates new form AppUi
     */
    public AppUi() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        buttonGroupTurno = new javax.swing.ButtonGroup();
        buttonGroupTitulacao = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldDisciplina = new javax.swing.JTextField();
        jRadioButtonMatutino = new javax.swing.JRadioButton();
        jRadioButtonVespertino = new javax.swing.JRadioButton();
        jRadioButtonNoturno = new javax.swing.JRadioButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldNome = new javax.swing.JTextField();
        jTextFieldEmail = new javax.swing.JTextField();
        jRadioButtonGraduacao = new javax.swing.JRadioButton();
        jRadioButtonMestrado = new javax.swing.JRadioButton();
        jRadioButtonDoutorado = new javax.swing.JRadioButton();
        jButtonIncluirAluno = new javax.swing.JButton();
        jButtonMostrarDados = new javax.swing.JButton();

        jScrollPane1.setViewportView(jTextPane1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Turma"));

        jLabel1.setText("Disciplina:");

        jLabel2.setText("Turno:");

        buttonGroupTurno.add(jRadioButtonMatutino);
        jRadioButtonMatutino.setText("Matutino");

        buttonGroupTurno.add(jRadioButtonVespertino);
        jRadioButtonVespertino.setText("Vespertino");

        buttonGroupTurno.add(jRadioButtonNoturno);
        jRadioButtonNoturno.setText("Noturno");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jRadioButtonMatutino)
                        .addGap(18, 18, 18)
                        .addComponent(jRadioButtonVespertino)
                        .addGap(16, 16, 16)
                        .addComponent(jRadioButtonNoturno)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jTextFieldDisciplina))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldDisciplina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jRadioButtonMatutino)
                    .addComponent(jRadioButtonVespertino)
                    .addComponent(jRadioButtonNoturno))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Professor"));

        jLabel3.setText("Nome:");

        jLabel4.setText("Email:");

        jLabel5.setText("Titulação:");

        buttonGroupTitulacao.add(jRadioButtonGraduacao);
        jRadioButtonGraduacao.setText("Graduação");

        buttonGroupTitulacao.add(jRadioButtonMestrado);
        jRadioButtonMestrado.setText("Mestrado");

        buttonGroupTitulacao.add(jRadioButtonDoutorado);
        jRadioButtonDoutorado.setText("Doutorado");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButtonGraduacao)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRadioButtonMestrado)
                        .addGap(18, 18, 18)
                        .addComponent(jRadioButtonDoutorado)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldNome, javax.swing.GroupLayout.DEFAULT_SIZE, 382, Short.MAX_VALUE)
                            .addComponent(jTextFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(22, 22, 22))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jRadioButtonGraduacao)
                    .addComponent(jRadioButtonMestrado)
                    .addComponent(jRadioButtonDoutorado))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jButtonIncluirAluno.setText("Incluir Aluno");
        jButtonIncluirAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIncluirAlunoActionPerformed(evt);
            }
        });

        jButtonMostrarDados.setText("Listar Dados da Turma");
        jButtonMostrarDados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMostrarDadosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonIncluirAluno)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonMostrarDados)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonIncluirAluno)
                    .addComponent(jButtonMostrarDados))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void setDisciplina() {
        String disciplina = jTextFieldDisciplina.getText();
        if (disciplina.trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "informe uma disciplina valida", "Erro", JOptionPane.ERROR_MESSAGE);
        } else {
            turma.setDisciplina(disciplina);
        }
    }

    public void setTurno() {
        if (jRadioButtonMatutino.isSelected()) {
            turma.setTurno(Turno.MATUTINO);
        } else if (jRadioButtonVespertino.isSelected()) {
            turma.setTurno(Turno.VESPERTINO);
        } else if (jRadioButtonNoturno.isSelected()) {
            turma.setTurno(Turno.NOTURNO);
        } else {
            JOptionPane.showMessageDialog(null, "Escolha um turno valido", "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }

    public void setProfessor() {
        String nome, email;

        if (jTextFieldNome.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Nome de professor invalido", "Erro", JOptionPane.ERROR_MESSAGE);
        } 
        if (jTextFieldEmail.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Email de professor invalido", "Erro", JOptionPane.ERROR_MESSAGE);
        } 
        else {
            nome = jTextFieldNome.getText();
            email = jTextFieldEmail.getText();

            professor.setEmail(email);
            professor.setNome(nome);
        }
    }
    
    public void setTitulacao() {
        if (jRadioButtonDoutorado.isSelected()) {
            professor.setTitulacao(Titulacao.DOUTORADO);
        } else if (jRadioButtonGraduacao.isSelected()) {
            professor.setTitulacao(Titulacao.GRADUACAO);
        } else if (jRadioButtonMestrado.isSelected()) {
            professor.setTitulacao(Titulacao.MESTRADO);
        } else {
            JOptionPane.showMessageDialog(null, "Escolha um titulo valido", "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void jButtonIncluirAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIncluirAlunoActionPerformed
        this.setDisciplina();
        this.setTurno();
        this.setProfessor();
        this.setTitulacao();

    }//GEN-LAST:event_jButtonIncluirAlunoActionPerformed

    private void jButtonMostrarDadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMostrarDadosActionPerformed
        String texto = " ";
        texto = "Disciplina: " + turma.getDisciplina() + "\n";

    }//GEN-LAST:event_jButtonMostrarDadosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AppUi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AppUi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AppUi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AppUi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AppUi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupTitulacao;
    private javax.swing.ButtonGroup buttonGroupTurno;
    private javax.swing.JButton jButtonIncluirAluno;
    private javax.swing.JButton jButtonMostrarDados;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton jRadioButtonDoutorado;
    private javax.swing.JRadioButton jRadioButtonGraduacao;
    private javax.swing.JRadioButton jRadioButtonMatutino;
    private javax.swing.JRadioButton jRadioButtonMestrado;
    private javax.swing.JRadioButton jRadioButtonNoturno;
    private javax.swing.JRadioButton jRadioButtonVespertino;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextFieldDisciplina;
    private javax.swing.JTextField jTextFieldEmail;
    private javax.swing.JTextField jTextFieldNome;
    private javax.swing.JTextPane jTextPane1;
    // End of variables declaration//GEN-END:variables
}
