/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.lista5.view;

import com.mycompany.lista5.model.Ponto;
import javax.swing.JOptionPane;

/**
 *
 * @author liandrar
 */
public class InterfacePonto extends javax.swing.JFrame {

    /**
     * Creates new form InterfacePonto
     */
    public InterfacePonto() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTxtFldX = new javax.swing.JTextField();
        jTxtFldY = new javax.swing.JTextField();
        jBtnAvaliar = new javax.swing.JButton();
        jCheckBoxIncideX = new javax.swing.JCheckBox();
        jCheckBoxIncideY = new javax.swing.JCheckBox();
        jCheckBoxPrimeiro = new javax.swing.JCheckBox();
        jCheckBoxSegundo = new javax.swing.JCheckBox();
        jCheckBoxTerceiro = new javax.swing.JCheckBox();
        jCheckBoxQuarto = new javax.swing.JCheckBox();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Eixo X:");

        jLabel2.setText("Eixo Y:");

        jLabel3.setText("Posição:");

        jBtnAvaliar.setText("Avaliar");
        jBtnAvaliar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAvaliarActionPerformed(evt);
            }
        });

        jCheckBoxIncideX.setText("Incide sobre o Eixo X");
        jCheckBoxIncideX.setEnabled(false);

        jCheckBoxIncideY.setText("Incide sobre o Eixo Y");
        jCheckBoxIncideY.setEnabled(false);

        jCheckBoxPrimeiro.setText("No 1º Quadrante");
        jCheckBoxPrimeiro.setEnabled(false);

        jCheckBoxSegundo.setText("No 2º Quadrante");
        jCheckBoxSegundo.setEnabled(false);

        jCheckBoxTerceiro.setText("No 3º Quadrante");
        jCheckBoxTerceiro.setEnabled(false);
        jCheckBoxTerceiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxTerceiroActionPerformed(evt);
            }
        });

        jCheckBoxQuarto.setText("No 4º Quadrante");
        jCheckBoxQuarto.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(55, 55, 55)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTxtFldY)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)
                                    .addComponent(jTxtFldX)
                                    .addComponent(jBtnAvaliar, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCheckBoxQuarto)
                            .addComponent(jCheckBoxPrimeiro)
                            .addComponent(jCheckBoxIncideY)
                            .addComponent(jCheckBoxIncideX)
                            .addComponent(jCheckBoxTerceiro)
                            .addComponent(jCheckBoxSegundo)
                            .addComponent(jLabel3))))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTxtFldX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addGap(3, 3, 3)
                .addComponent(jTxtFldY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(jBtnAvaliar)
                .addGap(33, 33, 33)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBoxIncideX)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBoxIncideY)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBoxPrimeiro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBoxSegundo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBoxTerceiro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBoxQuarto)
                .addContainerGap(41, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnAvaliarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAvaliarActionPerformed
        String xStr = jTxtFldX.getText().trim();
        String yStr = jTxtFldY.getText().trim();

        // Validação: campos vazios
        if (xStr.isEmpty() && yStr.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Valores de X e Y não podem ser vazios", "ATENÇÃO", JOptionPane.WARNING_MESSAGE);
            return;
        }
        if (xStr.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Valor de X não pode ser vazio", "ATENÇÃO", JOptionPane.WARNING_MESSAGE);
            return;
        }
        if (yStr.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Valor de Y não pode ser vazio", "ATENÇÃO", JOptionPane.WARNING_MESSAGE);
            return;
        }

        // Validação: apenas números inteiros (positivos ou negativos)
        if (!xStr.matches("-?\\d+")) {
            JOptionPane.showMessageDialog(null, "Valor de X deve conter apenas números inteiros", "ATENÇÃO", JOptionPane.WARNING_MESSAGE);
            return;
        }
        if (!yStr.matches("-?\\d+")) {
            JOptionPane.showMessageDialog(null, "Valor de Y deve conter apenas números inteiros", "ATENÇÃO", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        int x = Integer.parseInt(jTxtFldX.getText().trim());
        int y = Integer.parseInt(jTxtFldY.getText().trim());

        Ponto p1 = new Ponto(x, y);
        
        jCheckBoxIncideX.setSelected(false);
        jCheckBoxIncideY.setSelected(false);
        jCheckBoxPrimeiro.setSelected(false);
        jCheckBoxSegundo.setSelected(false);
        jCheckBoxTerceiro.setSelected(false);
        jCheckBoxQuarto.setSelected(false);
        
        if (p1.estaIncidindoSobreX()) {
            jCheckBoxIncideX.setSelected(true);
        }
        if (p1.estaIncidindoSobreY()) {
            jCheckBoxIncideY.setSelected(true);
        }

        switch (p1.identificarQuadrante()) {
            case PRIMEIRO:
                jCheckBoxPrimeiro.setSelected(true);
                break;
            case SEGUNDO:
                jCheckBoxSegundo.setSelected(true);
                break;
            case TERCEIRO:
                jCheckBoxTerceiro.setSelected(true);
                break;
            case QUARTO:
                jCheckBoxQuarto.setSelected(true);
                break;
        }
    }//GEN-LAST:event_jBtnAvaliarActionPerformed

    private void jCheckBoxTerceiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxTerceiroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBoxTerceiroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfacePonto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfacePonto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfacePonto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfacePonto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfacePonto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnAvaliar;
    private javax.swing.JCheckBox jCheckBoxIncideX;
    private javax.swing.JCheckBox jCheckBoxIncideY;
    private javax.swing.JCheckBox jCheckBoxPrimeiro;
    private javax.swing.JCheckBox jCheckBoxQuarto;
    private javax.swing.JCheckBox jCheckBoxSegundo;
    private javax.swing.JCheckBox jCheckBoxTerceiro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTxtFldX;
    private javax.swing.JTextField jTxtFldY;
    // End of variables declaration//GEN-END:variables
}
